# Controll Supervisor Add-on
name: "Controll Supervisor"
description: "Remote management for Controll platform"
version: "1.0.1"
slug: "controll_supervisor"
url: "https://controll.it"
arch:
  - aarch64
  - amd64
  - armv7
startup: "services"
boot: "auto"
init: false

# Permissions
hassio_api: true
hassio_role: "manager"
homeassistant_api: true

# Network
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Controll API"

# Map config folder
map:
  - config:rw

# Options
options:
  hub_token: ""
  platform_url: "https://api.controll.it"

schema:
  hub_token: str
  platform_url: url
